lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'YOUR_PASSPHRASE' # palavra-chave utilizada na geração das chaves
    token_ttl:  3600 # tempo de validade do token em segundos